# Generated by Django 4.2.9 on 2024-01-31 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_account_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='phone',
            field=models.CharField(default=0, max_length=14, unique=True),
            preserve_default=False,
        ),
    ]
