# Generated by Django 4.2.9 on 2024-03-13 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_otp_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='temp_data',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
