# Generated by Django 4.2.9 on 2024-02-01 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_account_email_alter_account_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='is_director',
            field=models.BooleanField(default=False, verbose_name='Director'),
        ),
        migrations.AlterField(
            model_name='account',
            name='is_farmer',
            field=models.BooleanField(default=False, verbose_name='Farmer'),
        ),
    ]
