# Generated by Django 4.2.9 on 2024-03-13 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_otp_temp_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otp',
            old_name='temp_data',
            new_name='signed_data',
        ),
        migrations.AlterField(
            model_name='otp',
            name='hash_key',
            field=models.CharField(max_length=6, primary_key=True, serialize=False),
        ),
    ]
