# Generated by Django 4.2.9 on 2024-02-07 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_directory', '0005_farmdirectory_lga_alter_farmdirectory_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmdirectory',
            name='state',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
